### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/MI-000-SS00-000-js-package-json-intro-AjvZZg#1]
@egillespie Can you take a look at this? It's [hosted here](https://katie-kg-tgc7noax99ajvzzg.surge.sh/) and meets the following criteria:

- [x] Start your project with [these old game files](https://gist.github.com/egillespie/61d72035cd8c2639f07db1dbe2010605)
- [x] Convert the game's CSS to Sass, using variables, functions, and nesting where appropriate
- [x] Write a `dev` script in `package.json` that auto-compiles Sass and refreshes the browser at the same time
- [x] Write a `build` script in `package.json` that lints HTML, Sass, and JavaScript files before compiling Sass files (you can use these linters: [htmlhint](https://www.npmjs.com/package/htmlhint) for HTML, [stylelint](https://www.npmjs.com/package/stylelint) for Sass, [standard](https://www.npmjs.com/package/standard) for JavaScript)
- [x] Write a `deploy` script in `package.json` that builds the project and uploads it to Surge if there are no errors
- [x] Unnecessary files like `node_modules` and your compiled CSS do not exist in your repository
- [x] Unnecessary files like `package.json` and `yarn.lock` are not uploaded to Surge

**Comment by egillespie** [comment]
I really like your Sass! I didn't realize how many opportunities there would be to nest styles. 👍 

It looks like you didn't commit `package.json` (and `yarn.lock`), so I'm unable to complete the review. Can you push those files and ping me when you want me to take another look?

**Comment by KatieMFritz** [comment]
Oh, I made an overly aggressive `.gitignore`:

```
node_modules/
compiled/

*.log*

.gitignore
node_modules
package.json
yarn.lock
```

Try now?

**Comment by egillespie** [comment]
Muy bien! Got you some feedback now:

### Note about `--fix`

In a work project I would avoid using `--fix` in a script because it modifies the file and won't put the result back into version control. I think it's better to use `--fix` once before committing your changes. For lots of JavaScript, writing those files could be time-consuming, too.

### Thoughts on `stylelint`

My intent was to have students use new dev dependencies that would require them to read docs and add them to the project. Do you think the median student would be able to figure out `stylelint` without our help?

**Comment by KatieMFritz** [comment]
Removed `--fix`. Thanks for the tip!

Regarding stylelint... I almost needed help, and I'd say I'm more experienced than the median student. 😕  But it's probably a good challenge. Also, by the time students get to this lesson, they will have a lot of experience in the class, so we can try it.

**Comment by egillespie** [comment]
Aww yeah :shipit:
